services:
  antigaspi-db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: Antigaspi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  antigaspi-api:
    build:
      context: ./backend-dotnet
      dockerfile: Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=antigaspi-db;Database=Antigaspi;Username=postgres;Password=postgrespassword
      # IMPORTANT: Change this in production!
      - JwtSettings__Secret=super-secret-key-that-is-at-least-256-bits-long
    ports:
      - "8080:8080"
    depends_on:
      - antigaspi-db

  antigaspi-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - antigaspi-api

volumes:
  postgres_data:
